language: php

php:
  - hhvm
  - nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

env:
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak
    - TARGET=test

matrix:
  fast_finish: true
  include:
    - php: 7.0
      env: TARGET=cs_dry_run
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest --prefer-stable"
    - php: 7.0
    - php: 5.6
      env: SYMFONY_VERSION=2.3.*
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.5
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*@dev
  allow_failures:
    - php: hhvm
    - php: nightly
    - env: SYMFONY_VERSION=3.0.*
    - env: SYMFONY_VERSION=3.1.*@dev

before_script:
  - mkdir -p ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d && echo "memory_limit=-1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - composer selfupdate
  - composer config -q github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - if [ "$SYMFONY_VERSION" = "2.8.*" ] || [ "$SYMFONY_VERSION" = "3.0.*" ] || [ "$SYMFONY_VERSION" = "3.1.*@dev" ]; then SYMFONY_DEPRECATIONS_HELPER=strict; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - travis_wait composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - make $TARGET
