<?php

/*
 * (c) Jérémy Marodon <marodon.jeremy@gmail.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Th3Mouk\YahooWeatherBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ForecastRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForecastRepository extends EntityRepository
{
    public function getForecasts(City $city)
    {
        $currentDate = new \DateTime();
        $lastForecastDate = new \DateTime();
        $dateInterval = new \DateInterval('P4D');
        $lastForecastDate->add($dateInterval);

        $qb = $this->createQueryBuilder('f')
            ->andWhere("f.date >= '".$currentDate->format('Y-m-d')."'")
            ->andWhere("f.date <= '".$lastForecastDate->format('Y-m-d')."'")
            ->andWhere('f.city = '.$city->getId())
        ;

        return $qb->getQuery()->getResult();
    }
}
